### ISSUE TITLE
Преводи за featured и за dump

### ISSUE THREAD

**Issue by v--** [stelf/en2bg4term#11]
Понеже не успях да измисля превод за гореспоменатите термини се надявам да помогнеш.

**Comment by ElitsaGKortenska** [comment]
dump буквално преведено е сметище, бунище; също - депо (в смисъла на депо за видове отпадъци) и  т.н., като глагол буквалния превод е захвърлям, изхвърлям. В разни документи поради 'липса' на превод пишат 'упражняват дъмпинг', а това е неадекватно. 
Но някой друг може да помогне с превод в ИТ контекс.

**Comment by IliaIdakiev** [comment]
За dump по-скоро изхвърлям.

**Comment by IliaIdakiev** [comment]
featured - препоръчан

**Comment by stelf** [comment]
значи dump в смисъка на data dump си е баш депо. изхвърлям е когато е действие. to dump data си е направо изхвърляне на данни, може е и да е свалям в депото.
