### ISSUE TITLE
breach

### ISSUE THREAD

**Issue by dragnev-dev** [stelf/en2bg4term#111]
От киберсигурност. Неоторизиран достъп (до данни, инфраструктура...).

П.С. постига се след пробив в система. Пробождане на системата (пак по-добре от _проникване_) и _пролив_ на данни – [да пролееш данните на цяла нация...](https://www.cnn.com/2019/07/21/europe/bulgaria-hack-tax-intl/index.html)

**Comment by stelf** [comment]
breach е пробив буквално. проникване, пробойна, нарушение (на кодекса). 

неоторизиран достъп е по-скоро illegal access, макар че го описва също да.

**Comment by stelf** [comment]
дописано, забравил съм да затворя.

breach | пробойна, пробив, проникване, нарушение | _в комп. сигурност. възможен синоним за vulnerability. и нищо общо с branch. виж #111_

**Comment by stelf** [comment]
👯
