### ISSUE TITLE
Какъв ще е превода на header? В контекста на HTTP header.

### ISSUE THREAD

**Issue by emdeha** [stelf/en2bg4term#13]
Аз си мисля за "глава", но някакси не ми звучи поетично. Друг вариант, за който се сещам е "заглавие" или "описание".

**Comment by ElitsaGKortenska** [comment]
оглававяне? оглавяващ може би?

**Comment by stelf** [comment]
заглавна част

**Comment by stelf** [comment]
...или увод

**Comment by emdeha** [comment]
Аз смятам, че заглавна част е най-лесно разбираемо.

**Comment by ElitsaGKortenska** [comment]
И аз мисля, че 'заглавна част' най-кратно и най-добре отразява за какво иде реч :)

**Comment by avelin** [comment]
антетка?

**Comment by avelin** [comment]
всъщност, като се замисля, "горен колонтитул" :)

**Comment by stelf** [comment]
горен колонтитул е техническия превод, обаче колонтитул е чуждица. "заглавна част" ми звучи за сега най-близо или може би пролог.

**Comment by vlood** [comment]
Преводът трябва освен да е превод, да значи нещо и за аудиторията, за която се превежда. Ако превеждате текст за уеб-програмисти или системни администратори и вкарате "горен колонтитул", адски много ще ви обичат :D

Коментарът ми не е градивен обаче. За това и аз подкрепям варианта за "заглавна част", така че "HTTP request header" да стане на "заглавната част на HTTP заявката", което що-годе подсказва за какво иде реч.

**Comment by hkdobrev** [comment]
Всичките headers на една HTTP заявка са заглавната част. "Body-то" е тялото. Но как се нарича точно един header, така че превода да има правилно контекстно значение е труден въпрос.

Някои груби предложения от мен:

- заглавен ред
- ред от заглавната част

---

Мисля, че уводната част на една заявка, би била TCP връзката.

**Comment by stelf** [comment]
@hkdobrev , заглавен ред или заглавна част.

**Comment by hkdobrev** [comment]
Аз бих избрал заглавен ред. Не бих казал, че е популярно, но не мисля, че и съществува популярен превод за header.

**Comment by vlood** [comment]
Заглавен запис?

**Comment by hkdobrev** [comment]
Намерих го преведено като "заглавно поле" - https://bg.wikipedia.org/wiki/MIME

Това също съвпада с Header fields използвано от Mozilla https://developer.mozilla.org/bg/docs/Web/HTTP/Headers.

**Comment by stelf** [comment]
в този ред на мисли, в речника има няколко термина, които си търсят смислени преводи. ако някому остане време е добре дошъл да дръпне един бърз прочит и да напляска тук теми за обсъждане.
