### ISSUE TITLE
А аналог на БГ за outlier (as in statistics)? 

### ISSUE THREAD

**Issue by ElitsaGKortenska** [stelf/en2bg4term#14]
Outlier(s) ме тормози от няколко дни и немога да го измисля. Преводите тук: http://www.ezikov.com/translate/outlier не са ми задоволителни сякаш. Търся единична дума или нещо по-кратко.Някой?

**Comment by stelf** [comment]
нещо като 'аномалия' може би? или частен случай?

**Comment by ElitsaGKortenska** [comment]
частен слуай точно мисля, че търсех.
