### ISSUE TITLE
Думи с повече от едно значение

### ISSUE THREAD

**Issue by googleson78** [stelf/en2bg4term#17]
Има някои думи, които имат повече от едно значение и не са дадени преводи за някои от тях. Би било полезно да присъстват и двете значения, по някакъв начин. (може би в скоби коя употреба се има предвид?)

Примери:
`map` е преведно като `карта, речник`, докато има и значението на функцията от по-висок ред [map](https://en.wikipedia.org/wiki/Map_(higher-order_function)).

`access` е преведено като `достъп`, докато има и друг смисъл като глагол. Българската дума `достъп` не може да се ползва по същия начин.

**Comment by stelf** [comment]
Напълно си прав. Давай заявки за сливане и да дописваме. Може и да те вкарам в хранилището директно.

Г
