### ISSUE TITLE
Clipboard

### ISSUE THREAD

**Issue by vlood** [stelf/en2bg4term#22]
Как, за Бога, го превеждате това? Не успях да намеря преводите на GNOME, където най-вероятно са му измислили нещо хитро...

**Comment by hkdobrev** [comment]
Буферна памет?

http://znam.bg/zmonres/edu/IT%209/lessons/os_disk/21.htm

Намирам известно количество страници в Google използващи буферна памет за clipboard. Но в същото време при превод в обратна посока, буферна памет може да бъде buffer storage, което има по общо значение.

**Comment by vlood** [comment]
Виждах го като буферна и временна памет, но за мен тези преводи са неподходящи. Пиша преводи за хората, които не са силно технически грамотни и които не знаят английски. Хем не е добре да остава клипборд, хем не е добре да замесваме памет в цялото нещо, камо ли пък буферна или временна.

За момента гледам да заобикалям превода, където е приложимо ("copy to clipboard" => "копиране"), но не навсякъде ще е възможно :/

**Comment by stelf** [comment]
предлагам следните, моля коментари

- табло за бележки
- табло обяви
- временен бележник
- бележник
- черна дъска

защото реално clip е нещо като прихващане, но може да е парче, може кламер да е. т.е. clipboard е мястото, където държим парчета с някакви временни записи.

btw, @vlood , copy си има превод на бг, а именно 'препис' :)

**Comment by hkdobrev** [comment]
> Виждах го като буферна и временна памет, но за мен тези преводи са неподходящи. Пиша преводи за хората, които не са силно технически грамотни и които не знаят английски. Хем не е добре да остава клипборд, хем не е добре да замесваме памет в цялото нещо, камо ли пък буферна или временна.

За този случай аз бих използвал специфичен превод в сферата за която е превода. Например, ако е софтуерно приложение, което има бележник, можеш да го въведеш като термин и всички други преводи да се въртят около него.

**Comment by metala** [comment]
буфер (табло, бележник) с записи / преписи

**Comment by sfbg** [comment]
"Междинна памет" сме го превели в Сейлфиш и смятам, че дава някаква идея за какво  става въпрос

**Comment by vlood** [comment]
Ако не можем да избегнем "памет", междинна ми звучи най-добре :)

Затварям задачата, пък си преценяйте дали това ще влиза в официалния речник тук.

**Comment by sfbg** [comment]
Не мисля, че "памет" трябва да се избегне на всяка цена.
Добавих го в заявкати ми за сливане, тогава.
