### ISSUE TITLE
Превод на Interface

### ISSUE THREAD

**Issue by stelf** [stelf/en2bg4term#23]
някой може ли да предложи читав превод на interface, може и жаргон, защото за сега нищо не излиза...? 

като съществително е нещо като 'способ за взаимодействие', като глагол е май само 'взаимодействие'

няколко вида интерфейси има: 

- програмен, в смисъла на API
- мрежови
- потребителски (в смисъла на изглед)

**Comment by hkdobrev** [comment]
Аз предложих #18, но осъзнавам, че не е униврсално.

**Comment by hkdobrev** [comment]
Затварям го, защото след #23, @stelf merge-на (сля) #18, но може пак да се отвори, ако има по-хубав превод.
