### ISSUE TITLE
превод на bandwidth

### ISSUE THREAD

**Issue by stelf** [stelf/en2bg4term#24]
понастоящем е записан 'дебит', но това май пак е чуждица от латинското _debitum_.

**Comment by hkdobrev** [comment]
За мен дебит е много точен превод и много разпространена дума в българския. Ако гледаме произход на думите, които дори са влезли в книжовния език (или поне тълковния речник на българския език), тогава много от преводите трябва да ги преработим.

**Comment by sfbg** [comment]
**Дебит** е най-близък и според мен.
**Попускливост**, **проводимост**?

**Comment by stelf** [comment]
окей, навивам се за дебит да остане, може би все пак и ‘ширина на връзката’?

ширина - width
превръзка, връв - band

?

**Comment by stelf** [comment]
и 'обем на канала' заедно с 'ширина на връзката' ? ... и оставяме дебит като трето предложение (макар дебит/кредит да имат друг смисъл във финансовия контексТ)

**Comment by metala** [comment]
'честотна лента' е единият термин, който отговаря на bandwidth. За другия, аз ползвам 'капацитет на канала', но и двете са заемки.

**Comment by orlin369** [comment]
@metala , бих добавил ширина на лената. Така с превежда в радио честотната техника. Исзползва се точно за дебит, или възможност на лената (канала) да пренесе нещо (данни).

**Comment by stelf** [comment]
ок, честотна лента... плюс ... плюс иде ми да кажа дебит, но лошото е, че момчетата финансисти много лошо са узурпирали думата дебит в смисъла на директен дЕбит (ударение в/у Е-то) и се ползва за добиване на средства.

 https://bg.wiktionary.org/wiki/%D0%B4%D0%B5%D0%B1%D0%B8%D1%82
