### ISSUE TITLE
chat

### ISSUE THREAD

**Issue by sfbg** [stelf/en2bg4term#34]
Аз лично не съм чак толкова против "чат", но разбира се, не оптимално.
Един приятел настоява, че "лафче" е добър компромис.

**Comment by metala** [comment]
Раздумка?

**Comment by sfbg** [comment]
> Раздумка?

Много симпатично звучи като съществително и ми харесва.
Как би бил глаголът "чатя", обаче?

**Comment by metala** [comment]
Да, 'лафче' и 'лафя' имат предимство, че са доста близки.

Иначе за глагол, бих предложил 'приказвам' и израза 'на (по) приказка', вместо съществително име.

**Comment by hkdobrev** [comment]
А защо не просто "разговор"?

chat (v.) като глагол - разговарям.

На английски се използва и за чат със съобщения и за разговор на живо и по телефона. "Разговор" е тази дума на български според мен.

**Comment by sfbg** [comment]
Разговор е по-формално и отговаря на conversation по-скоро.
Бъбрене и бъбря е по-близо, като се замисля.

Мислехме и за беседа, беседвам, но пак е доста формално. А chat Определено не е.

**Comment by stelf** [comment]
*лаф* става, но е доста жаргонно. и бих се усъмнил, че е от друг език, ама кой. 

руснаците и те я знаят тая дума https://ru.wiktionary.org/wiki/%D0%BB%D0%B0%D1%84

**Comment by sfbg** [comment]
@stelf _лаф_ е на турски за _дума(не)_. И затова не ме въудушевява толкова.
Дир.бг имаха преди 20 години доста полулярна услуга, базирана на ICQ май, която се казваше "Лафче".

_Бъбря_ ми става все по-симпатично.

**Comment by sfbg** [comment]
Уф, не знам. **Разговор** е нещо съвсем друго според мен, формално.

**Comment by stelf** [comment]
раздумка 😄 🤣

**Comment by sfbg** [comment]
Супер като съществително, но няма глагол... :/

**Comment by metala** [comment]
Добре, защо не две отделни думи - раздумка и (по)приказвам.

**Comment by sstoyanov7** [comment]
Няма как да преведем една дума като "chat" с много английски значения на български с една, две думи. Тука става дума за превод на "on-line chat" и "chat room/group",  а не на общaта дума "chat", нали?

Допълнитено трябва да имаме в предвид, че:
а) трябва да имаме превод като на глагол и съществително, както се спомена.
б) определени чуждици носят допълнителна информация. Пр. "разговря" и "чатихме"  са две различни действия. При едното има говор, а при другото писане.
г) хубаво е да се има в предвид конекста на превода в изречение. 

Бих се спрял на: 
- гл. бъбря, (по)приказвам при говор
- гл. пиша при on-line chat, така се избягват две думи и чуждица като "онлайн разговор"
- същ. лафче, чат (изключвам раздумка, защото предполага говор)

Примерно използвам:
"We chatted" =  "Бъбрихме си/Приказвахме си" (при говор и не е уточнено къде)
"We chatted in Skype" = Писахме си в Skype (при писане)
"We met in a on-line chat" = "Запознахме се в чата/на лафче" (не е уточнен кой чат/сайт)
"We chatted in IRC" - глагола няма значение, защото IRC позволява само за писане.

**Comment by stelf** [comment]
* бъбря +1
* пиша ... м не точно
* лафчето все пак може да се спомене, макар че е от турски

**Comment by stelf** [comment]
@sfbg според

https://ibl.bas.bg/rbe/lang/bg/%D0%BB%D0%B0%D1%84/

лаф е от персийски, така че не е съвсем турска. значи и чадър и цифра са от персийски и арабски, но няма какво да правим. нямаме от махалата наши :)

**Comment by stelf** [comment]
@sfbg -> [раздумване](https://ibl.bas.bg/rbe/lang/bg/%D1%80%D0%B0%D0%B7%D0%B4%D1%83%D0%BC%D0%B2%D0%B0%D0%BD%D0%B5/) и [раздумка](https://ibl.bas.bg/rbe/lang/bg/%D1%80%D0%B0%D0%B7%D0%B4%D1%83%D0%BC%D0%BA%D0%B0/) може би са окей... и съм навит и за [лаф](https://ibl.bas.bg/rbe/lang/bg/%D0%BB%D0%B0%D1%84/), предвид, че сигурно е на 1000 години...

@metala  @sstoyanov7

**Comment by metala** [comment]
всичките ме радват, с изключение на "разговор".
