### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by sfbg** [stelf/en2bg4term#38]
Няма я тук, а и аз нямам добри идеи...

**Comment by vlood** [comment]
В WordPress официално го превеждаме като "разширение", иначе съм го виждал и като "добавка" на разни места. Add-on и extension са синоними в контекста на софтуер, така че от горните две се ползва това, което е най-подходящо за случая.

**Comment by sfbg** [comment]
Приставка е супер!
Другите също нека да се добавят, защото има и други контексти.

**Comment by stelf** [comment]
говтово в 2d3467a
