### ISSUE TITLE
обща бърза среща по време на отворения фест

### ISSUE THREAD

**Issue by stelf** [stelf/en2bg4term#41]
по време на OpenFest възнамерявам да спамя с #29 и предлагам в тоя ред на мисли да си направим една очна ставка :) 

предложения и коментари в този поток.

**Comment by stelf** [comment]
- постановка на таблицата
- разделяне или не в азбучен ред
- широко обнародване на речника
- къде е границата на преводите, отвъд която изпадаме в крайности

**Comment by stelf** [comment]
понеже никой не се отзова, бързо резюме:

* отпечатах 6000 лепенки, имам още - който иска да каже да му пратя
* представих като бърза лекция речника. имаше незабавна реакция. има смисъл да се представя и на други места

**Comment by vlood** [comment]
Ще е яко някакви стикери да имаме в init Lab, най-малкото WordPress преводачите се събираме там, но и други хора могат да подочуят за проекта.

**Comment by stelf** [comment]
ще занеса, имам достатъчно. стига да са окей.

**Comment by stelf** [comment]
@vlood , май все така забравям да занеса, а има един 'кашон'. да пратя по пощата?

**Comment by vlood** [comment]
Не знам защо не съм отговорил до сега, но ако все още е при теб кашона - пращай към офис на Еконт - ул. Козлодуй, пък от там ще го съберем като пристигне :)

**Comment by stelf** [comment]
има доста дам. ще гледам да засиля тия дни , сори. кого да адресирам? маниакса :)) ?

**Comment by vlood** [comment]
Владимир Василев, Маниакса надали ще се вясва скоро към Лаба.

**Comment by stelf** [comment]
затварям го това, нещо не успяваме да направим организация, с тоя ковид най-много _на живо_ през екраните да го докараме.
