### ISSUE TITLE
Common name (CN)

### ISSUE THREAD

**Issue by sfbg** [stelf/en2bg4term#45]
При SSL удостоверения...

**Общо наименование** може би? Така го намерих тук: https://support.brother.com/g/s/id/htmldoc/ads/ads2600w/bg/html/nug/chapter7_6_2.html

**Comment by metala** [comment]
"Общо име" е по-кратко и има същото значение. Но верятно има и по-подходящ превод, който да е по-близо до значението.
Имам съмнение, че "common" не е "общ", а по-скоро нещо като  colloquial name, trivial name, popular name. Точно това "common name" е преведено като "народно име" на холандски и македонски. 

Моето предложение е "обикновено име".

**Comment by stelf** [comment]
"обичайно име" предлагам

**Comment by sfbg** [comment]
[Тук има примери](https://www.linguee.com/english-bulgarian/search?source=auto&query=%22common+name%22) от други контексти, но според мен същото значение. Проеводачите в ЕС нямат явно общ подход.

Най-подходящо там ки се видя **общоприето наименование**.

@stelf може да го скъсим и приближим до твоето първо предложение:

- общоприето име

Но на мен даже наименование ми харесва повече.

**Comment by stelf** [comment]
да изберем най-краткото.... което може би е 

- прието име

**Comment by sfbg** [comment]
Има разика между прието и общоприето. Common за мен е второто.

**Comment by sstoyanov7** [comment]
"Прието име" се губи значението.
"Общоприето име" по-добре. 

"Общоизвестно име" още по-добре. От същия [линк](https://www.linguee.com/english-bulgarian/search?source=auto&query=%22common+name%22) посочен от @sfbg. Защото с него съм общо известен на обществото, а не то е приело как да се казвам аз или организацията ми.

**Comment by stelf** [comment]
* общоприето + 1
* общоизвестно + 1

и заедно да влязат?

**Comment by sfbg** [comment]
@stelf, да, слагай и двете в тази последователност и затваряй.
