### ISSUE TITLE
audit trail

### ISSUE THREAD

**Issue by stelf** [stelf/en2bg4term#46]
audit trail ?

* следа
* проследяване на действията

почва вече да ми се иска да мислим нови думи, сглобени от корените на съществуващи такива...

**Comment by metala** [comment]
Второто добре посочва за какво служи. Audit tail е синоним за audit log, т.е. записки от проверка / одит.

Предлагам 'записи от надзор'. Това показва, е има контрол (надзор) на действията и в същото време показва, че се водят записки.

**Comment by stelf** [comment]
вкарвам и двете, добре звучи това, което предлага @metala , ще пиша "проследяване на действията" като втори превод.
