### ISSUE TITLE
world wide web

### ISSUE THREAD

**Issue by stelf** [stelf/en2bg4term#50]
така 

получи се следното запитване .) 

и предложението съответно... вие как смятате?

![image](https://user-images.githubusercontent.com/785435/71998276-fe601d00-3247-11ea-8a73-9a832114bf70.png)

**Comment by sfbg** [comment]
Подкрепям. Мисля, че съм го виждал така и в много текстове.

**Comment by metala** [comment]
+1 за "световната мрежа" и определено е по-добре членувано, за разлика от това което е вписано в Уикипедия.
