### ISSUE TITLE
avatar?

### ISSUE THREAD

**Issue by vlood** [stelf/en2bg4term#52]
Google го предлага като "въплъщение", ама мен малко ме тревожи възможността хората да влизат в настройките на каквото и да било, за да си променят въплъщението...

**Comment by metala** [comment]
Буквално си е въплъщение, но ако искаш контекстов синоним - 'лице' в смисъл на persona, мисля че е подходящо.

**Comment by vlood** [comment]
В контекста на уеб приложения клоня към „лична снимка“, бидейки най-близко до същността на термина. В изречения като "Update your avatar" не се сещам за нещо друго, което да не звучи нелепо :/

**Comment by sstoyanov7** [comment]
"Лична снимка" предполага фотография. В този случай е по-добре да се използва портрет.
Предлагам "лик", което е свързанo с лице, по-общо е от снимка и е различно от образ/image.

**Comment by stelf** [comment]
бих заложил на въплъщение, защото аватар-а въплащава нещо в нещо. лик става като някакъв синоним, така че 

* въплащение + 1
* лике + 1

**Comment by stelf** [comment]
ping, @vlood, @metala

**Comment by vlood** [comment]
Вероятно „лик“ е най-близо до това, което трябва да бъде, и то само защото се опасявам, че някой може да се задави, ако прочете „обновете въплъщението си“ в някой нехумористичен интерфейс.

**Comment by stelf** [comment]
@vlood , мисля, че лий е много добре като начало -> предлагам да го вкарваш. 'обнови лика' си или 'нов лик' или дори 'смени си облика' е супер.

**Comment by vlood** [comment]
https://github.com/stelf/en2bg4term/pull/58
