### ISSUE TITLE
State, stateful, stateles

### ISSUE THREAD

**Issue by sfbg** [stelf/en2bg4term#55]
Аз съм за сътоветно:
**състояние
състоятелен
безсъстоятелен** (видяно само [тук](https://cio.bg/sigurnost/2012/07/06/3444837_forrester_mobilnite_ustroistva_iziskvat_cialostna/), но все пак)

**Comment by stelf** [comment]
@vlood , @metala ако нямате забележки към, този - да го придвижа, че станаха две години...  (fyi @sfbg )

**Comment by vlood** [comment]
Със състояние съм окей, предвид че вероятно може да се ползва в по-широк контекст, докато "състоятелен" и "безсъстоятелен" ми звучат твърде абстрактни. Бих подходил по-описателно - нещо от рода на "с поддържана на сървъра потребителска сесия" и "без поддържана на сървъра сесия". Сървър и сесия са чуждици, ама в момента просто не мога да отделя времето за сглабяне на нещо по-читаво, за да изразя мнението си точно.

**Comment by stelf** [comment]
stateless може да се напише като [ефимерен](https://bg.wiktionary.org/wiki/%D0%B5%D1%84%D0%B8%D0%BC%D0%B5%D1%80%D0%B5%D0%BD), което според братушките е на заем от съседите гърци

_Происходит от прил. [эфемерный](https://ru.wiktionary.org/wiki/%D1%8D%D1%84%D0%B5%D0%BC%D0%B5%D1%80%D0%BD%D1%8B%D0%B9), из [др.-греч.](https://ru.wiktionary.org/wiki/%D0%B4%D1%80%D0%B5%D0%B2%D0%BD%D0%B5%D0%B3%D1%80%D0%B5%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D1%8F%D0%B7%D1%8B%D0%BA) [ἐφήμερος](https://ru.wiktionary.org/w/index.php?title=%E1%BC%90%CF%86%CE%AE%CE%BC%CE%B5%CF%81%CE%BF%CF%82&action=edit&redlink=1) «[однодневный](https://ru.wiktionary.org/wiki/%D0%BE%D0%B4%D0%BD%D0%BE%D0%B4%D0%BD%D0%B5%D0%B2%D0%BD%D1%8B%D0%B9); годный на день» из [ἐπί](https://ru.wiktionary.org/wiki/%E1%BC%90%CF%80%CE%AF#%D0%94%D1%80%D0%B5%D0%B2%D0%BD%D0%B5%D0%B3%D1%80%D0%B5%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9) «[на](https://ru.wiktionary.org/wiki/%D0%BD%D0%B0), [при](https://ru.wiktionary.org/wiki/%D0%BF%D1%80%D0%B8), [за](https://ru.wiktionary.org/wiki/%D0%B7%D0%B0), [согласно](https://ru.wiktionary.org/wiki/%D1%81%D0%BE%D0%B3%D0%BB%D0%B0%D1%81%D0%BD%D0%BE)», из праиндоевр. *op- «[сзади](https://ru.wiktionary.org/wiki/%D1%81%D0%B7%D0%B0%D0%B4%D0%B8), [вокруг](https://ru.wiktionary.org/wiki/%D0%B2%D0%BE%D0%BA%D1%80%D1%83%D0%B3)» + [ἡμέρα](https://ru.wiktionary.org/wiki/%E1%BC%A1%CE%BC%CE%AD%CF%81%CE%B1) «единица времени, [день](https://ru.wiktionary.org/wiki/%D0%B4%D0%B5%D0%BD%D1%8C)»._

**Comment by metala** [comment]
Аз лично бих ползвал - състояние-имащ и състояние-нямащ. Например, състояние-нямащи функции при безсървърни изчисления. Но не мисля, че ще се приеме от общността.

Състоятелен има значение на обоснован, основателен, както и обратното на несъстоянетелен. 

Проблемът с ефимерен е, че вече се ползва при други обстоятелства, като обемни дялове за контейнери, както и в тайнописа - временни скрити ключове, които се ползват еднократно при установяване на връзка (пр. ECDHE).

**Comment by sfbg** [comment]
Май и аз вече съм за:
**"имащ състояние"
"нямащ състояние"**

Безсъстоятелен има негативна конотация, която тук не е на място,

Да го слагаме така и да се приключва, а?

**Comment by stelf** [comment]
@sfbg дума [несъстоятелен](http://ibl.bas.bg/rbe/lang/bg/%D0%B1%D0%B5%D0%B7%D1%81%D1%8A%D1%81%D1%82%D0%BE%D1%8F%D1%82%D0%B5%D0%BB%D0%B5%D0%BD/) нямат в БАН, имат [несъстоятелен](http://ibl.bas.bg/rbe/lang/bg/%D0%BD%D0%B5%D1%81%D1%8A%D1%81%D1%82%D0%BE%D1%8F%D1%82%D0%B5%D0%BB%D0%B5%D0%BD/),  което е друго май...?

имащ/нямащ състояние е най-близкото, което за сега хрумва.
