### ISSUE TITLE
Няколко термина около конкурентност и паралелизъм

### ISSUE THREAD

**Issue by vladimiroff** [stelf/en2bg4term#57]
Има няколко термина, в тази област, за които не ми хрумва адекватен превод:

- `mutex`: това ще е тегаво, предвид факта, че самата "дума" е странно съкращение на "mutual exclusion"
- `race condition`: имам някакви спомени, че това съм го виждал да се превежда като "критична точка", но ми се струва като доста неконкретно
- `data race`
- `deadlock`
- `livelock`

**Comment by stelf** [comment]
@vladimiroff , направо ни разби :) много добре наистина да се помисли, можеш ли да дадеш някакви идеи твои...просто на прима виста. ето от мен

* mutex: тъй като това е нещо, което се ползва за взаимно изключване на две неща, е хубаво или а) да измислим дума, която комбинира и двете и б) да се мисли жаргон. не се сещам
* race condition: случва се някаква надпревара (състезание) или по-точно създават се условия, при които две неща (процеси примерно) се състезават/надпреварват за трето (данни, код, етц.) . така че _условие за състезание_ или _конкурентна ситуация_ (което си е с чуждици)  или дрои.. _условия за надпревара_
* data race - отново - състезание, надпревара за данни. 

така бих обощил, че всичките 'race'-ове са надпревара/състезание за кой ще 'докопа' (access) пръв нещото

* deadlock - чиста проба _фльонга_ :)), бих предложил и жаргона _закучка_ от закучило се е нещо. обаче май това не е книжовна дума... 
* livelock - това ако е -> [това](https://www.guru99.com/what-is-livelock-example.html) <- нямам идея на този теап, но и не съм го срещал много, честно казано, мисля че е по-ново като понятие.

**Comment by vladimiroff** [comment]
Тези са ми в главата от известно време, с презумпцията "като се сетя за добри преводи, ще ги изпратя". Минаха месеци и добри преводи не дойдоха, затова питам :confused: 

> - mutex: тъй като това е нещо, което се ползва за взаимно изключване на две неща, е хубаво или а) да измислим дума, която комбинира и двете и б) да се мисли жаргон. не се сещам

По принцип mutex е синоним на lock (https://en.wikipedia.org/wiki/Lock_(computer_science)). В такъв случай "ключалка" звучи сравнително добре. 

> -    deadlock - чиста проба фльонга :)), бих предложил и жаргона закучка от закучило се е нещо. обаче май това не е книжовна дума...

Това ми звучи супер. То и mutex не е книжовна дума, ама се използва.

> -   livelock - това ако е -> това <- нямам идея на този теап, но и не съм го срещал много, честно казано, мисля че е по-ново като понятие.

Да, това е. Водейки се по твоята идея, какво ще кажеш за "активна закучка"?
