### ISSUE TITLE
middleware

### ISSUE THREAD

**Issue by stelf** [stelf/en2bg4term#59]
предлагам: 

* посредник
* средина

терминът се ползва в express.js, но мисля, че се появява и друг път като някакво средно нещо. ако правехме думи като англо-говорящите, щяхме да кажем 'междинност' ... 

https://www.redhat.com/en/topics/middleware/what-is-middleware

**Comment by vladimiroff** [comment]
> ако правехме думи като англо-говорящите, щяхме да кажем 'междинност'

Интересно, защо на български "междиден" да не звучи добре? Междинна функция и междиден (модул|клас|метод) ми звучат доста добре.

Интересно е обаче колко неадекватно звучи, ако тръгнем да превеждаме и "ware" (пример: "Междинно изделие").

**Comment by stelf** [comment]
> Интересно, защо на български "междиден" да не звучи добре?
може би защото не middleware не е прилагателно, и това ни трябва някакво съществитлно. иначе самата дума 'междинен' не звучи зле и от там *междинен слой* е възможен превод, макар и от две думи. 

подозирам, че някой JS фен ще се метне да обяснява, че middleware не е цял слой, а в някои случаи част от програмата. но ако ви звучи окей "междинен слой, междинен" като превод го въвеждаме. 

гласувам все пак и за "средина", което според читанката е книжвна дума - https://rechnik.chitanka.info/w/%D1%81%D1%80%D0%B5%D0%B4%D0%B8%D0%BD%D0%B0

@sstoyanov7 @vladimiroff

**Comment by vlood** [comment]
„Междинен слой“ звучи достатъчно ясно. За разлика на него, ако чуя „средина“ в технически контекст, ще се чудя какво е искал да каже авторът.

**Comment by sfbg** [comment]
Има го и в стопанските информационни тейхнологии.
"Средина" е неразбираемо за мен. "Междинен слой" се доближава повече.
"Спойка", "Свръзка"?

**Comment by stelf** [comment]
@sfbg, **_спойка_** е това, което се превежда като **_solder_**... а и middleware не винаги е свързващият/спояващ слой, по-скоро се явява като допълнение, което застава м/у два други. 

руснаците дават превод "промежуточное программное обеспечение", което всъщност навежда на мисълта, че middleware може да се преведе като промеждутък (същ.) или промеждутъчен (прил.) и би ми се искало да го преведа като _промежду**тие**_, но такава дума няма. няма и _**про**междина_, което съвсем би било middleware :) 

бтв, руснаците изглежда казват _промежина_ на това, което медиците наричат перинеум. а според преводачаката един македонец би ползвал _среден софтвер_, за да опише middleware на мајчинскиот јазик.

**Comment by vlood** [comment]
В европейски правни документи middleware е преведено "междинен продукт":

It will include middleware for the management, control and use of fully distributed resources...
Те ще обхванат междинните продукти за управление, контрол и употреба на изцяло разпределени ресурси...

Източник: https://app.glosbe.com/tmem/show?id=-3649809125277327061

Бих подкрепил следните варианти:

- междинен продукт
- междинен слой
- междинна програма
- междинен софтуер

Очевидно влизат чуждици, пък някои не са ок със слой, но не виждам по-добър вариант, който да не е объркващ.

**Comment by kunev** [comment]
И на мен най-ясно ми се струва „междинен слой“. Съвсем разбираемо е в софтуерен контекст, без да е непременно неразривно свързано с него (както биха били „междинен софтуер“ и до някаква степен „междинна програма“). Като според контекста „слой“ винаги може да се заменя с нещо по-конкретно: „функция“, „клас“, „програма“, „устройство“ и прочее.
„Средина“, „спойка“ и „свръзка“ определено бих ги ползвал, защото са супер яки думи, но не бих очаквал да бъда особено добре разбран.
