### ISSUE TITLE
Предложение за по-добър превод на "Bug"

### ISSUE THREAD

**Issue by byrtolet** [stelf/en2bg4term#61]
На мен много ми харесва "bug" на български да се нарича "гъба".

Първо, както бъговете пропълзяват в кода, по аналогия гъбите могат да израстнат навсякъде из кода.

Отделно може да се замени побългареното "сбъгяса се" със "сгъбяса се"

И е кратко и ясно.

**Comment by stelf** [comment]
привет,

сгъбяса се е интересно предложение за жаргон. важно е да отбележим, че е подходящо по-скоро защото звучи по същия другата дума. т.е. пароними са.  сякаш съм чувал да се ползва... 'сгъбяса се'. само дето те, бъговете (или гъбовете ако предпочиташ), не се появяват сами. т.е. има си ги изначално, заложени са, те са недостатък, порок който е неволно вкаран от сътворителя на програмата.

освен това - гъбите са всъщност плодните тела на мицела. мицелът, това скритото нещо, е живо и прораства на определени места, но не винаги скапва нешата. даже напротив - спомага за преноса на вещества м/у растенията и т.н. тоест гъбясването е по-скоро проява на недостатъците на програмите, а не самите недостатъци.

_в тоя ред на мисли е крайно време вероятно да разделим преводите на такива, които са смислови (т.е. дословни, книжовни и т.н.) и такива, които са жаргонни и там да запишем предложението. защото някои жаргони са смислени, дори като омоними. а и като цяло тук определящо е дали масата ще възприеме дадената дума, дали ще я припознае и повтори._ 

за бъг знам един друг жаргон - прокапка, който точно отразява memory leak.

**Comment by byrtolet** [comment]
Не знам точно какво имате пред вид под "жаргон." По принцип, и английските термини са т.н. "професионален жаргон". Тоест ние се опитваме да създадем аналогичен професионален жаргон на български.
В общя случай буквалния превод рядко е най-подходящия. Много рядко се срещат двойки думи (камо ли изрази) в различните езици, които да са със еднакъв смисъл и същите нюанси.
Отделно мисля че не е ужасително, когато няма добър превод и да се заемат думите (тоест да се ползват както в оригинал, или леко побългарени). В крайна сметка това е един от начините за обогатяване на езика. 
Основна цел на термините е да улесняват комуникацията, но за целта трябва и двете страни участващи в комуникацията да са наясно с тях. Това най-лесно се постига, когато въпросните термини се срещат в книги, и се ползват от преподавателите, при обучението. За съжаление, много от  авторите и преподавателите не си правят труда да подберат подходящи. В този ред на мисли искам да кажа че идеята за този речник е много добра.

**Comment by sfbg** [comment]
На мен "буба" ми идва с прекалено положителни конотации, заради коприната. Колкото повече, по-добре.

"Гнида", от друга страна ми харесва много и ми звучи като свеж жаргон.

**Comment by byrtolet** [comment]
Аз също харесвам много повече гнида от колкото буба, да не говорим че гнидите могат да се крият из кода дълго време преди да се "излюпят" тоест проявят...

**Comment by sstoyanov7** [comment]
Окей, съм за гнида.

**Comment by stelf** [comment]
@sstoyanov7 @metala като е гнида, да е плесен направо? че не звучи толко гнусно поне...

**Comment by metala** [comment]
Не всички плесени са токсични за хората. Всички знаем, че пеницилина е от плесен и никак не ми се връзва с "bug". От друга страна гнидата е яйце, нещо заложено. Ако погледнем метафорично, това е нещо което чака удобни условия да се изклюпи и за да направи поразии. Освен това, гнидите често могат да се премахват механично, докато плесента изисква по-специална обработка.

Относно гнусността на термина, нямам коментар. И двете са ми еднакво негнусни.

**Comment by stelf** [comment]
окей значи хрумна ми следното, което е кратко и не гнусно и описателно:

**недъг**

даже има 2 от буквите на бъг и една, която се пише по подобен начин (българското д, не руското, разбира се .)

**Comment by byrtolet** [comment]
"Недъг" е много хубаво и описва много точно част от бъговете.  На мен лично ми харесва.
Но има разни нюанси в думата, които не винаги се връзват. 

Но винаги може да се разширяват значенията на думите.

Има го и по-големия проблем - дори да се съгласим 100 човека, да ползваме някаква дума не е ясно как тази дума би стигнала до всички, които я използват.

Освен това, няма нужда да се ограничаваме до само една дума. Както на времето имаше една дума за компютърен вирус, а после се появиха всякакви троянци, червеи и тем подобни.

Разбира се, винаги можем да кажем, че бъг е рекурсивен акроним (backronym):

бъг = бъг е грешка!

**Comment by stelf** [comment]
@byrtolet по въпросите ти:

* с тия неща няма как да накараш някой да хареса нешо на сила. Даваш му предложение, а той избира. Също така повечето преводи, тези дето са поели отговорност за течнима, ги вкарват с пълната увереност, че са така и без да питат народа .)
* това за бекронима е супер и ще ср наложи за фа успокоим духовете

Предлагам и още една дума - кусур. Твърди се че е от турски произход, но kusura било съжаление на турски. Та ще питам в НГДЕКа как я виждат .)

_за *гнидата* съм почти навит да я запишем също и ще стане ‘пощене’ за debug … нал’тъй? 😝😃 @metala, живи да са родителите ти, че се включих със здрав разум._
