### ISSUE TITLE
Emergence

### ISSUE THREAD

**Issue by metala** [stelf/en2bg4term#65]
Интересно явление, където обект проявява свойства неприсъщи за отделните му части, в следствие на взаимодействието на елементите в система. По-точното определение на английски е следното:
'emergence' occurs when an entity is observed to have properties its parts do not have on their own, properties or behaviours which emerge only when the parts interact in a wider whole[1].

Открих го, след като човек в Туитър даде учудващо добра дефиниция за интеграционен тест: 'tests where emergence is a viable source of error, such that each component can be working correct in isolation but in aggregate things fail'[2].

Въпреки, че по-буквалния превод би бил нещо като 'появност' или 'появяване', моето предложение е 'проявност', от проява на свойства.

_______
1. https://en.m.wikipedia.org/wiki/Emergence
2. https://mobile.twitter.com/hillelogram/status/1485748417309642763

**Comment by stelf** [comment]
в буквален превод би било нещо от следните

* проявление (макар че за това има и думата apparition)
* (предложеното от теб) поява
* [прииждане](https://bg.wiktionary.org/wiki/%D0%BF%D1%80%D0%B8%D0%B8%D0%B6%D0%B4%D0%B0%D0%BD%D0%B5)

по-скоро въпросът е дали е ИТ термин изобщо това или го е употребил човек0т в твитер като някаква речева форма...?

**Comment by metala** [comment]
Това е термин от системната теория и си мисля, че е приложима в нашата сфера. Напоследък се заравям в TLA+ и моделиране на системи и съм с убеждението, че формалните методи ще се развиват и хората ще започнат да ги ползват все по-често и тази терминология ще навлезе.

Предлагам следното, да затворим темата, а след време ако има интерес, то всеки може да пише и да я отвори наново.

**Comment by stelf** [comment]
@metala връзката в уикипедия, която даваш определено е от сферата на философията... можеш ли да дадеш връзка към някакви други писания по темата?
