### ISSUE TITLE
Misuse

### ISSUE THREAD

**Issue by xAl3xFx** [stelf/en2bg4term#67]
Според мен misuse е по-скоро грешна употреба, отколкото злоупотреба. Abuse може да се каже, че е злоупотреба.

**Comment by stelf** [comment]
вероятно и двете са верни, в случая, а и според доста речници са синоними. злоупотреба би следвало да е по-конрекнто misappropriation, особено ако става дума за злоупотреба със средства. ще допиша и _грешна употреба_, ако се сетиш за нещо, което е една дума и се произнася по-лесно (на БГ) е добре дошло.
