### ISSUE TITLE
Commit (като съществително)

### ISSUE THREAD

**Issue by icostaykov** [stelf/en2bg4term#68]
**Commit**, освен като глагол, се използва и като съществително - главно в git системите. Как може да се преведе на български?

**Comment by stelf** [comment]
@vlood , @metala има и нещо друго, което е, че 'to commit oneself to smtng' е в смисъла да се отдам, посветя на нещо.

**Comment by vladimiroff** [comment]
В българската локализация на git е преведено като "подаване":

```
--> git status
На клон master
Клонът е обновен към „origin/master“.

Промени, които ще бъдат подадени:
  (използвайте „git restore --staged ФАЙЛ…“, за да извадите ФАЙЛа от индекса)
        нов файл:          XXX

Промени, които не са в индекса за подаване:
  (използвайте „git add ФАЙЛ…“, за да обновите съдържанието за подаване)
  (използвайте „git restore ФАЙЛ…“, за да отхвърлите промените в работната директория)
        променен:          XXXX

Неследени файлове:
  (използвайте „git add ФАЙЛ…“, за да определите какво включвате в подаването)
        XXX
```

```
--> git pull
error: не може да извършите „издърпване с пребазиране“, защото има промени, които не са в индекса.
error: трябва да подадете или скатаете промените.
```

**Comment by stelf** [comment]
забавен е превода на 'stash' -> 'скатавам' :) макар че според речника 'скатавам' е stow... но бих се навил.

мисълта ми е - странно звучат малко изреченията в тоя превод. все едно не е търсена яснота на превода, а просто самоцелност някаква.

например "Changes to be committed"  е по-скоро "подготвени промени" или "промени очакващи запис" или "промени в обхват на текуща промяна". 

а как точно от "Changes not staged for commit" се стигна до "промени, които не са в индекса за подаване" не знам... би ме накарало веднага да сменя цялата локализация обратно към английски. какво пречеше да напишат "промени, които не са в списъка за запазване" ? или "промени извън обхвата на запис" ...?

някак не може да ме убедят тия преводи, че стават за пътеводна светлина и някакъв мерител за вярност.

**Comment by stelf** [comment]
тъй като имаме агенция по вписванията и commit е в някакъв смисъл запис/вписване на нещо, може да предложим 'вписване' -> има такова съществително всъщност https://bg.wiktionary.org/wiki/%D0%B2%D0%BF%D0%B8%D1%81%D0%B2%D0%B0%D0%BD%D0%B5

**Comment by vlood** [comment]
> @vlood , @metala има и нещо друго, което е, че 'to commit oneself to smtng' е в смисъла да се отдам, посветя на нещо.

Отдаванията и посвещенията ми се струват съвсем далече от техническия контекст, та бих предложил спокойно да подминем това значение на думата. "Вписване" започва много по-добре да звучи след последния ти коментар.

**Comment by metala** [comment]
Правил съм регистрова система и смятам вписване съответства на нов запис с промени. Ново вписване (в регистъра).
