### ISSUE TITLE
Иван Богоров и думата влак

### ISSUE THREAD

**Issue by metala** [stelf/en2bg4term#70]
Увода включва пасаж, който коментира приноса на Иван Богоров за българския език:
> ..., за него днес мнозина биха казали, че е бил още по-краен - създал е и въвел нови чисто български думи със ясно значение като 'влак', 'часовник' и 'вестник'.

Виждам, че се споменява думата 'влак', а аз бях останал с впечатление, че е заемка от чешкия език. Възможно ли е чехите да са я взели от нас? Има ли източник, който да разяснява произхода на думата 'влак'?

**Comment by stelf** [comment]
Прав ще излезеш, @metala , поне според

https://ibl.bas.bg/lib/ber/#page/256/mode/1up

и

<img width="637" alt="Capture d’écran 2022-09-15 à 11 37 48" src="https://user-images.githubusercontent.com/785435/190357024-8ea12bdd-4a18-488b-acf4-a9fcbb2bee53.png">

чудно нещо е езика. какво да правим сега? предложения за пренаписване на увода?

**Comment by metala** [comment]
То и на немски Zug май идва от ziehen - влача.

**Comment by stelf** [comment]
променен е увода без влака, пък другото нека стои... :)
