### ISSUE TITLE
header

### ISSUE THREAD

**Issue by sfbg** [stelf/en2bg4term#76]
Има го два пъти, но не ми е ясно защо и какво е "горен колонтитул". 

Спонтанно винаги бих казал **заглавка**. Литературно значи начална голяма буква на абзац, но гледам в търсачките, че определено се ползва и за header в живия живот, което е добре дошло. Думата е хубава и кратка.

**Comment by vlood** [comment]
На места го пишем "заглавна част" и много рядко "горна част" в контекста на уеб.

"Горен колонтитул" го намирам за неподходящо по никакъв начин бидейки специализиран печатарски термин. "Заглавка" също го избягвам, макар че някои колеги преводачи го ползват в WordPress, без да се е наложил там. Бидейки със значение, различно от "заглавната част" на какъвто и интерфейс да говорим, ми се струва неподходящ превод.

Ако пък говорим за хедър на файл или някаква заявка, тогава никое от по-горе посочените не важат ама може би е добре тук да уточним кой контекст адресираме.

**Comment by stelf** [comment]
това... заглавка може и да е възможен превод, макар според БАН да има [малко по-различно значение,](http://ibl.bas.bg/rbe/lang/bg/%D0%B7%D0%B0%D0%B3%D0%BB%D0%B0%D0%B2%D0%BA%D0%B0/) но предвид, че е кратко и ясно предлагам да го запишем. оче повече е дума, която излиза от употреба и вместо да виси в речника като нещо остаряло може да и дадем нов смисъл. а и има "глава".

тоя горен колонтитул беше предложен от @kunev ако помня правилно, но ще се изненадаш - макар и чуждица, съзставена от две други (colon + title), тази дума някой умник от БАН я е вкарал в [речника](http://ibl.bas.bg/rbe/lang/bg/%D0%BA%D0%BE%D0%BB%D0%BE%D0%BD%D1%82%D0%B8%D1%82%D1%83%D0%BB/). в тоя ред на мисли 'горен' е излишно, защото е той е _горен_ така или иначе.
