### ISSUE TITLE
patch

### ISSUE THREAD

**Issue by vladimiroff** [stelf/en2bg4term#78]
Буквалният превод "кръпка" или "закърпим" (to patch) е нещо, което ми звучи достатъчно добре.

От друга страна, днес ми попадна превода "адаптация", който ми се стори толкова крайно некоректен, че реших да видим дали някой ще измисли нещо по-подходящо от "кръпка".

**Comment by vlood** [comment]
Кръпка си го ползвам дори в ежедневието, говорейки с клиенти и колеги, та не бих го заменил за нещо друго.

Адаптация може да се ползва само от някой, който не иска или не може да си признае, че кодът му всъщност е имал бабалюги :D
