### ISSUE TITLE
bottleneck

### ISSUE THREAD

**Issue by ChrisChoBG** [stelf/en2bg4term#90]
В понс предлагат:
недостиг [o. дефицит]

**Comment by stelf** [comment]
bottleneck е точно гърлото на бутилката (врата в буквално буквален превод). 

тапата е това, дето го затапва. може би за жаргон се ползва, ама тук се има предвид не това, което предизвиква задръстването в стеснения участък, а самият "стеснен участък". което е възможен превод. 'тясно място' е възприет в някои случаи превод. има и думата '[теснотия](https://ibl.bas.bg/rbe/lang/bg/%D1%82%D0%B5%D1%81%D0%BD%D0%BE%D1%82%D0%B8%D1%8F/)' и '[теснота](https://ibl.bas.bg/rbe/lang/bg/%D1%82%D0%B5%D1%81%D0%BD%D0%BE%D1%82%D0%B0/)'.

**Comment by dragnev-dev** [comment]
Притягане, за да избегнем неудобното стеснение.

> тапа

Пробка формално. Чеп, грездей.

**Comment by stelf** [comment]
@dragnev-dev , да нямаш предвид по-скоро [пристягане](https://ibl.bas.bg/rbe/lang/bg/%D0%9F%D1%80%D0%B8%D1%81%D1%82%D1%8F%D0%B3%D0%B0%D0%BD%D0%B5/), което е доста приемливо сякаш? и е дума, нещеш ли... така че предлагам заедно със [стеснение](https://ibl.bas.bg/rbe/lang/bg/%D1%81%D1%82%D0%B5%D1%81%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5/) и да си стиснем ръцете :)

**Comment by dragnev-dev** [comment]
> [пристягане](https://ibl.bas.bg/rbe/lang/bg/%D0%9F%D1%80%D0%B8%D1%81%D1%82%D1%8F%D0%B3%D0%B0%D0%BD%D0%B5/) заедно със [стеснение](https://ibl.bas.bg/rbe/lang/bg/%D1%81%D1%82%D0%B5%D1%81%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5/) и да си стиснем ръцете

Да, що не :))

> за bottleneck point [чувам за пръв път](https://en.wikipedia.org/w/index.php?search=Bottleneck+point&title=Special%3ASearch&ns0=1)

Я е валиден, я не – опитах се да покрия други случаи на употреба, но май изгубих смисъла
